services:
  web-server:
    build: web-server
    ports:
      - 127.0.0.1:9002:80
    env_file:
      - ${ENVIRONMENT}.env
      
    restart: unless-stopped

  signaling-server:
    build: signaling-server
    restart: unless-stopped
    ports:
      - 127.0.0.1:9002:8001
